import {label as musicLabel} from './musicLabels'
const labels:Record<string,string>={
  "SnapGoodSEName": "滑动终点Good音效名称",
  "TaskMusic03": "任务 03 的歌曲 ID 列表",
  "JudgeScoreRateMarverous": "Marvelous 判定倍率",
  "Level02": "等级02",
  "Level": "与该行关联的玩家等级",
  "TrophyCategory": "奖杯分类",
  "BoostType02": "增益类型02",
  "MultiPlayVsPointBonusRateLevel01": "多人游玩对战点数奖励比例等级01",
  "SuccessSoundPath": "交易成功提示音资源路径",
  "HoldNoteDivisionLaneWidth": "长按音符分割轨道宽度",
  "bValidCulture_ja_JP": "日文地区可用标志",
  "ButtonWidgetColor": "按钮外观颜色",
  "RewardInfernoMusicIdArray": "额外的 Inferno 曲目 ID 列表",
  "TextureSize": "图标尺寸",
  "Level03": "等级03",
  "PosY": "Y 坐标分量",
  "BonusItemCategory": "附加商品类别",
  "MultiPlayVsPointBonusRateLevel13": "多人游玩对战点数奖励比例等级13",
  "DifficultyHardLv": "Hard 等级定数",
  "MenuCharaMes": "角色台词/提示文案的本地化键",
  "ConditionRecoveryLife": "条件恢复生命",
  "ClearNormaRateInferno": "通关通关标准比例地狱",
  "GoodTimingRear": "Good时机后侧",
  "ClearNormaRateNormal": "通关通关标准比例普通",
  "ButtonIconType": "Button图标类型",
  "NotesColorType": "对应 ENotesColorType",
  "HoldMarvelousName": "长按Marvelous名称",
  "StoreMenuCharaMessage": "商店菜单角色消息",
  "PosX": "X 坐标分量",
  "ClearNormaRateExtreme": "通关通关标准比例专家",
  "ItemNum": "主商品数量，写入购买请求",
  "TimeLimitUpRate": "时间限制增加率参数",
  "BrandId": "电子货币品牌编号",
  "MovieAssetNameExpert": "Expert 专用 MV 名",
  "AssetDirectory": "歌曲资源目录/文件基名，例如 S03-030",
  "BonusItemId": "附加商品 ID",
  "ChangeGuideLaneAppearanceComboBorder": "变化Guide轨道外观连击Border",
  "ScoreGenre": "歌曲流派分类",
  "PenaltyNoteRateNormal": "Penalty音符比例普通",
  "ArtistMessage": "艺术家/作者名",
  "ItemTexture": "商品图片资源名",
  "SugorokuID": "Gate 活动编号，用来把本行归入同一活动",
  "MessageTag": "卡片消息标签",
  "ConditionLife": "条件生命",
  "TaskGenre01": "任务 01 的曲风代码",
  "Value00": "条件参数一",
  "StartDateTime": "开始日期时间",
  "ConditionGetableEndTime": "可获得结束时间字段",
  "NotesScoreRate": "音符分数倍率",
  "TaskMusicBonus02": "任务 02 相关分数参数",
  "MarvelousPopEffectName": "Marvelous 判定触摸特效资源名",
  "TextFontSizeA": "主文案字号",
  "BonusItemNum": "附加商品数量",
  "PageNumber": "同一 Gate 活动内的页序",
  "AnnounceEndDate": "公告结束时间",
  "VIPJoinedLightMaterialName": "VIP 画面的灯光材质名",
  "SeeYouStageupTextureName": "阶段升级结束画面的角色纹理名",
  "StoreMenu": "商店菜单",
  "BoostItemType": "道具类别，使用 EBoostItemType",
  "ItemActivateStartTime": "商品开始时间",
  "VIPJoinedTextureName": "VIP 加入画面的角色纹理名",
  "bVipPreOpen": "VIP 提前开放",
  "TextFontSizeB": "第二段文案字号",
  "Level07": "等级07",
  "BonusMarvelousPopEffectName": "Bonus Marvelous 判定触摸特效资源名",
  "BaseScoreNormal": "普通用户的基础分数参数",
  "RequiredDate": "所需日期",
  "GuideLaneBrightnessParamGradationMovie": "播放影片时的渐变参数，当前为 6",
  "TaskMusic01": "任务 01 关联的歌曲 ID 列表",
  "ConditionGenre": "条件类别",
  "TargetAchievementRateSSS": "SSS 目标达成率阈值，当前 0.97",
  "ID": "行内记录 ID",
  "SheetNumberList": "本奖励规则适用的 Sheet 编号集合",
  "BoostRate02": "增益比例02",
  "TitleNameTag": "标题文本键",
  "ConditionGetableStartTime": "可获得起始时间字段",
  "NavigateCharacterIds": "活动标题/导航角色 ID 列表",
  "EndDate": "开放期结束时间，现有值同样形如 YYYYMMDDHH",
  "JudgeScoreRateGreat": "Great 判定倍率",
  "JudgeScoreRateMiss": "Miss 判定倍率",
  "AppearConditionArray": "Appear条件数组",
  "JudgeScoreRateGood": "Good 判定倍率",
  "MovieAssetName": "基础 MV 名，通常供 Normal 使用",
  "DefaultTextureName": "默认贴图名称",
  "DifficultyInfernoLv": "Inferno 等级定数",
  "GreatPopEffectName": "Great 判定触摸特效资源名",
  "CrearBonusRateS": "S 成绩奖励倍率",
  "PenaltyNoteRateInferno": "Penalty音符比例地狱",
  "ImplementationSeason": "实装赛季",
  "SkillLevel": "技能等级",
  "ButtonTextTagA": "主文案的 SystemMessage 行名",
  "PenaltyNoteRateExpert": "Penalty音符比例专家",
  "AnnounceStartDate": "公告开始时间",
  "ChainSeName": "Chain 音效名称",
  "Rubi": "歌名读音",
  "PlayMusicNumPassword": "与歌曲数量设置相关的密码值",
  "BoostType03": "增益类型03",
  "PlayTime": "浮点数",
  "TouchEffectId": "触摸特效 ID",
  "RequiredExp": "字段名表示该等级所需经验值",
  "PosZ": "Z 坐标分量",
  "MusicUniqueIDArray": "本关的曲目 ID",
  "ErrorSoundPath": "交易失败提示音资源路径",
  "VIPJoinedBackGroundMaterialName": "VIP 画面的背景材质名",
  "GoldClearLife": "达到 Gold 通关等级相关的生命阈值",
  "OptionSettingTexture": "设置页相关纹理资源名",
  "RandomEndPlayCardInfoList": "随机结束卡片列表，元素结构见下方",
  "MonitorTextureName": "屏幕贴图名称",
  "SheetNumber": "Bingo Sheet 编号",
  "CrearBonusRateFullCombo": "Full Combo 奖励倍率",
  "bValidCulture_h_Hans_CN_GeneralMember": "简体中文普通会员标志",
  "MenuIconTexturePath": "菜单图标贴图路径",
  "BonusGreatPopEffectName": "Bonus Great 判定触摸特效资源名",
  "AddPlayMusicNum": "206002 当前为 1",
  "TicketId": "票券ID",
  "FullComboBonus": "完整连击奖励",
  "ParamMes": "字符串",
  "TitleActionMessageTag": "活动操作/提示消息标签",
  "MultiPlayVsPointBonusRateLevel15": "多人游玩对战点数奖励比例等级15",
  "HoldEffectName": "Hold 特效资源名",
  "ReHoldSEName": "再次长按音效名称",
  "MisslessBonus": "无失误奖励",
  "ItemId": "奖励物品 ID",
  "TitleBalloonWidgetPath": "标题活动气泡 Widget 类路径",
  "GreatTimingFront": "Great时机前侧",
  "MultiPlayVsPointBonusRateLevel06": "多人游玩对战点数奖励比例等级06",
  "CountryCode": "行对应的地区代码",
  "TargetAchievementRateS": "S 目标达成率阈值，当前 0.9",
  "SheetEndNum": "该配置结束编号",
  "TrophyId": "奖杯 ID",
  "HitRate": "候选物品的命中权重/概率相关整数",
  "Reserved": "保留字段",
  "WaccaPointCost": "歌曲解锁所需 Wacca Point（WP 价格）",
  "TicketType": "沿用现有值 0，除非已确认枚举和值的读取逻辑",
  "BoostType01": "增益类型01",
  "GoodsId": "商品编号",
  "IconId": "图标 ID",
  "LimitationTime": "对应页面/流程的时间数值，类型为 32 位浮点数",
  "SubErrorNum": "错误子编号，用来区分同一个主编号下的具体错误",
  "GoodTimingFront": "Good时机前侧",
  "isExpertOpen": "表字段名如此",
  "bValidCulture_h_Hans_CN_VipMember": "简体中文 VIP 标志",
  "CharaType": "与 ECharacterType 的 0–11 对应",
  "Level09": "等级09",
  "SubSeasonId": "Bingo 子赛季编号",
  "Level15": "等级15",
  "Value2": "数值2",
  "BoostItemId": "道具编号",
  "Priority": "候选消息优先级",
  "VIPJoinedFrontMaterialName": "VIP 画面的前景材质名",
  "CrearBonusRateSS": "SS 成绩奖励倍率",
  "MarvelousSEName": "Marvelous音效名称",
  "BoostRate03": "增益比例03",
  "MusicTagForUnlock1": "歌曲标签用于解锁1",
  "MaxPossessionNum": "正数表示限制",
  "Green": "绿色通道",
  "MusicTagForUnlock8": "歌曲标签用于解锁8",
  "ConditionType": "条件类型，数值对应 EConditionType",
  "UserPlateBacgroundTextureName": "贴图资源名",
  "isOriginalCharacter": "是否为 Original 导航员",
  "StageClass": "关卡分类编号",
  "MusicUniqueID": "歌曲唯一ID",
  "SkillType": "技能类型",
  "ItemActivateEndTime": "商品结束时间",
  "MissionNumList": "按相同数组位置，配置对应任务档位的任务数量",
  "NormaRate": "Norma 比率",
  "SugorokuStageName": "Gate 活动名称的本地化 key",
  "MusicTagForUnlock7": "歌曲标签用于解锁7",
  "MultiPlayVsPointBonusRateLevel03": "多人游玩对战点数奖励比例等级03",
  "BgChangeRate": "背景变化率",
  "ConditionKeys": "条件键",
  "RequiredScore": "该等级配置的最低分数门槛",
  "DifficultyExtremeLv": "Expert/Extreme 等级定数",
  "MultiPlayVsPointBonusRateLevel02": "多人游玩对战点数奖励比例等级02",
  "bIsInitItem": "初始商品",
  "MissEffectName": "Miss 判定触摸特效资源名",
  "SugorokuSelectCenterImage": "Gate 活动选择界面相关的图片资源路径",
  "NormaGaugeGood": "Good 判定的 Norma 数值",
  "SymbolColorId": "符号颜色 ID",
  "HashTag": "歌曲标签文字",
  "FlawlesslyMissCount": "完美Miss数量",
  "NormaGaugeJust": "Just 判定的 Norma 数值",
  "EndContentsStartUserLevel": "结束内容开始玩家等级",
  "PenaltyNoteRateHard": "HARD 难度的 miss 惩罚比率，当前 0.06",
  "HasLoopPage": "是否启用 Gate 循环页设置",
  "Level05": "等级05",
  "CompetitionModePassword": "Competition Mode 相关密码",
  "ExclusionTargetGoodsId": "排除目标商品ID",
  "TitleCallVoiceMessages": "标题呼叫语音消息标签列表",
  "SeeYouRankInTextureName": "排名/名次结束画面的角色纹理名",
  "ColorParameterName": "颜色Parameter名称",
  "BoostValue04": "增益数值04",
  "NormaPassEffectWaitTime": "Norma 通过效果的等待时间，当前为 10.0",
  "Red": "红色通道",
  "bRequirePurchase": "需要购买",
  "MusicTagForUnlock6": "歌曲标签用于解锁6",
  "RewordWaccaPoint": "字段原名拼作 Reword",
  "bValidCulture_h_Hans_CN": "可用区域 h_Hans_CN",
  "BoostValue01": "增益数值01",
  "CrearBonusRateMaster": "Master 成绩奖励倍率",
  "IconRarity": "图标稀有度数值",
  "GuideLaneBrightnessParamAlphaNormal": "普通画面下引导线亮度参数，当前为 600",
  "AdaptedStartDashLevel": "起始 Dash 等级相关参数，当前为 4",
  "bValidCulture_zh_Hant_TW": "繁体中文（台湾）可用标志",
  "AdjustRateFront": "调整比例前侧",
  "MusicTagForUnlock3": "歌曲标签用于解锁3",
  "ButtonTextTagB": "第二段文案的 SystemMessage 行名",
  "AdaptEndTime": "生效结束时间",
  "WorkBuffer": "工作缓存",
  "TargetAchievementRateMaster": "Master 成绩目标达成率阈值，当前 1.0",
  "VoiceActivateEndTime": "导航员语音启用时间窗的结束值",
  "SubstituteWaccaPoint": "替代为 Wacca Point 时使用的数值",
  "Alpha": "透明度通道",
  "UserPlateBacgroundRarity": "玩家名牌背景稀有度",
  "UserPlateBackgroundId": "背景物品 ID",
  "Value4": "数值4",
  "MultiPlayVsPointBonusRateLevel08": "多人游玩对战点数奖励比例等级08",
  "bValidCulture_en_US": "英文（美国）可用标志",
  "IconTexturePath": "道具图标资源路径",
  "Blue": "蓝色通道",
  "TargetPoint": "本页各奖励档位对应的目标点数",
  "PlayMusicNumMax": "可选歌曲数量上限",
  "PenaltyMissJudgeNum": "miss 惩罚相关的判定数量",
  "CrearBonusRateSSS": "SSS 成绩奖励倍率",
  "MultiPlayCoopPointBonusRate": "Coop 模式的点数加成率",
  "bValidCulture_Offline": "离线模式可用标志",
  "bRecommend": "推荐曲标志",
  "NotesDesignerInferno": "音符谱师地狱",
  "SaleStartDate": "销售开始时间字段",
  "BoostValue03": "增益数值03",
  "Level06": "等级06",
  "AchievementBonusScoreRate": "成绩率奖励分数倍率",
  "EventID": "活动编号",
  "HelpTextTag": "按键帮助提示的 SystemMessage 行名",
  "GetItemValue": "获得道具数值",
  "BackGroundMaterialPath": "背景材质路径",
  "GoodEffectName": "Good 判定触摸特效资源名",
  "SeeYouNormalTextureName": "普通结束画面的角色纹理名",
  "GreatShootEffectName": "Great Shoot 特效资源名",
  "RewardGatePoint": "奖励Gate点数",
  "bValidCulture_ko_KR": "韩文地区可用标志",
  "NormaGaugeSuperJust": "SuperJust 判定的 Norma 数值",
  "MultiBonus": "多人游玩相关的分数参数",
  "bEnableCoinblockerSetting": "EnableCoinblocker设置",
  "SugorokuCenterImage": "Gate 活动中心图片资源路径",
  "GradePartsId02": "第二个部件 ID",
  "WaccaPointUpRate": "Wacca Point 增加率参数",
  "EasingDay": "时间/日期样式的活动字段",
  "TaskMusicBonus01": "任务 01 相关分数参数",
  "CountMusicNum": "数量歌曲数量",
  "TaskGenre03": "任务 03 的曲风代码",
  "bValidCulture_NoneActive": "字段名表示无活动/非激活状态标志",
  "StageType": "Stage 类型",
  "StartDate": "开放期开始时间",
  "NotesColorId": "音符颜色ID",
  "MusicMessage": "歌曲标题",
  "SlideGoodSEName": "滑动Good音效名称",
  "ClearAnimationType": "通关演出等级",
  "DifficultyNormalLv": "Normal 等级定数",
  "BpmBorder": "BPM 边界值",
  "bValidCulture_en_SG": "英文（新加坡）可用标志",
  "GainWaccaPoint": "获得 WACCA 点数",
  "RandomMessageConditionType": "随机消息条件类型",
  "MusicTagForUnlock2": "歌曲标签用于解锁2",
  "HoldInputEffectName": "Hold 输入特效资源名",
  "GradePartsId01": "第一个部件 ID",
  "TargetAchievementRateSS": "SS 目标达成率阈值，当前 0.93",
  "GradeRarity": "Grade 稀有度数值",
  "BoostValue05": "增益数值05",
  "MarvelousTimingFront": "Marvelous时机前侧",
  "Condition": "条件代码",
  "ReHoldEffectName": "ReHold 特效资源名",
  "BasicExp": "基础 EXP 参数，当前为 25",
  "ParamName": "字符串",
  "MusicTagForUnlock5": "歌曲标签用于解锁5",
  "GradePartsType": "类型字段对应 EGradePartsType",
  "MainSeasonId": "Bingo 主赛季编号",
  "LaunchDate": "运营日期（YYYYMMDDHH）",
  "GradePartsId": "部件 ID",
  "MultiPlayVsPointBonusRateLevel04": "多人游玩对战点数奖励比例等级04",
  "MaterialName": "评级对应的材质资源名",
  "CrearBonusScoreRate": "清除/通关奖励分数倍率",
  "MultiPlayVsPointBonusRateLevel12": "多人游玩对战点数奖励比例等级12",
  "TrainingLevel": "训练/新手引导级别（0..3）",
  "RequiredInfernoOpenWaccaPoint": "Inferno 开放所需点数",
  "RankInEndPlayCardInfoList": "排名结束卡片列表，元素结构见下方",
  "NotesDesignerNormal": "音符谱师普通",
  "StoreMenuDescription": "商店菜单说明",
  "NameTag": "名称",
  "PreviewBeginTime": "选曲试听音乐起始播放时间点（单位",
  "EventMusicTag": "活动歌曲标签",
  "SnapMarvelousSEName": "滑动终点Marvelous音效名称",
  "BoostType05": "增益类型05",
  "CopyrightMessage": "版权文字",
  "ColorNameTag": "颜色名称键",
  "CrearBonusRateHalfCombo": "Half Combo 奖励倍率",
  "BoostValue02": "增益数值02",
  "Level04": "等级04",
  "ButtonWidgetType": "按钮布局类型",
  "ReplaceString": "标签在该配置下替换成的文字",
  "StageId": "关卡 ID",
  "ValidCultures": "语言区域到启用状态的映射",
  "MultiPlayVsPointBonusRateLevel11": "多人游玩对战点数奖励比例等级11",
  "MissionMusicID": "任务/关卡关联歌曲 ID",
  "UnlockConditionArray": "解锁条件数组",
  "ClearRate": "通关率/清除率相关数值",
  "MusicId": "歌曲 ID",
  "RequiredRate": "所需比例",
  "bValidCulture_en_HK": "英文（香港）可用标志",
  "MultiPlayVsPointBonusRateLevel09": "多人游玩对战点数奖励比例等级09",
  "Step": "阶段",
  "MultiPlayVsPointBonusRateLevel10": "多人游玩对战点数奖励比例等级10",
  "GradeId": "称号ID",
  "HoldNoteDivisionLength": "Hold 音符分段长度，当前为 2.0",
  "NoteSpeedRate": "音符速度倍率参数，当前为 2.0",
  "bWaccaOriginal": "WACCA 原创曲标志",
  "BoostRate04": "增益比例04",
  "GuideLaneBrightnessParamAlphaMovie": "播放影片时的引导线亮度参数，当前为 290",
  "LevelList": "该 Sheet 区间中出现的任务档位",
  "ClearNormaRateHard": "通关通关标准比例困难",
  "Value1": "数值1",
  "HoldColorNumber": "颜色序号字段，当前值覆盖 0–12",
  "CalcRateCoefficient": "Calc比例系数",
  "bValidCulture_h_Hans_CN_Guest": "简体中文游客标志",
  "Value5": "数值5",
  "AdjustRateRear": "调整比例后侧",
  "ExplanationTextTag": "说明文本",
  "DifficultyArray": "每首曲目的难度，必须与曲目数组逐项对应",
  "Value01": "条件参数二",
  "Price": "按 PayableType 指定货币解释的价格",
  "MarvelousTimingRear": "Marvelous时机后侧",
  "Value3": "数值3",
  "MultiPlayVsPointBonusRateLevel05": "多人游玩对战点数奖励比例等级05",
  "AdditionalMissNorma": "额外 miss Norma 调整值",
  "RequiredMusicOpenWaccaPoint": "开放所需点数",
  "VoiceActivateStartTime": "导航员语音启用时间窗的起始值",
  "UniqueID": "歌曲 ID，也是 DataTable 行名",
  "JacketAssetName": "封面资源名，例如 S03/uT_J_S03_30",
  "ProtectInvolveRockFrameNum": "保护关联锁定帧数量",
  "ConditionId": "条件编号",
  "NotesDesignerExpert": "音符谱师专家",
  "SlideMarvelousSEName": "滑动Marvelous音效名称",
  "StageupTextureName": "升级/阶段变化时使用的角色资源名",
  "Level01": "等级01",
  "Level13": "等级13",
  "ItemNumber": "奖励数量",
  "TrophyRarity": "奖杯稀有度",
  "TitlaCallVoiceCharacterIds": "标题呼叫语音相关角色 ID 列表",
  "ErrorNum": "错误主编号",
  "SESetID": "音效套装编号，与行名一致",
  "SkillID": "技能 ID",
  "SilverClearLife": "达到 Silver 通关等级相关的生命阈值",
  "ImageFileName": "字符串",
  "GradePartsId03": "第三个部件 ID",
  "MusicTagForUnlock9": "歌曲标签用于解锁9",
  "GoodSEName": "Good音效名称",
  "PayableType": "支付方式，使用 EPayableType",
  "ConditionJudge": "条件所使用的判定名称",
  "bSecretMusicFlgArray": "每首曲目对应的隐藏曲标志",
  "EventFlg": "活动标志",
  "SeeYouCondition": "结束卡片条件枚举",
  "AssetFullPath": "运行时谱面目录",
  "MenuName": "菜单项标题对应的文本键",
  "HoldSEName": "长按音效名称",
  "TaskMusic02": "任务 02 的歌曲 ID 列表",
  "NormaGaugeMiss": "Miss 判定的 Norma 数值",
  "Difficulty": "难度编号",
  "Level14": "等级14",
  "VersionNo": "选曲版本分组值",
  "RequiredHitCount": "所需击中数量",
  "WaccaPoint": "该行对应的 Wacca Point 数量",
  "BoostType04": "增益类型04",
  "ItemUseSceneFlag": "复用现有可使用票券时保留 true",
  "MusicTagForUnlock4": "歌曲标签用于解锁4",
  "Level08": "等级08",
  "FirstPlayBonus": "首次游玩奖励相关参数",
  "Level11": "等级11",
  "MultiPlayVsPointBonusRateLevel14": "多人游玩对战点数奖励比例等级14",
  "TaskGenre02": "任务 02 的曲风代码",
  "bConditionLimitNowSeason": "是否仅限当前赛季",
  "SaleEndDate": "销售结束时间字段",
  "BeatTiming": "节拍时机",
  "ItemCategory": "主商品类别代码",
  "TexturePosition": "图标放左侧还是右侧",
  "SymbolColorFileName": "符号颜色材质/资源路径片段",
  "Level12": "等级12",
  "NotesDesignerHard": "音符谱师困难",
  "TaskMusicBonus03": "任务 03 相关分数参数",
  "NavigateCharacterID": "导航员 ID",
  "NormaUpRate": "Norma 增加率参数",
  "MovieAssetNameInferno": "Inferno 专用 MV 名",
  "GreatTimingRear": "Great时机后侧",
  "MusicTagForUnlock0": "歌曲标签用于解锁0",
  "BoostRate01": "增益比例01",
  "IconTextureName": "图标贴图名称",
  "BoostSuccessJudgeNum": "加成相关的成功判定数量",
  "RewardItemArray": "关卡奖励物品 ID",
  "BaseScoreVip": "VIP 用户的基础分数参数",
  "bIsSupportColor": "Support Color 分类标记",
  "MultiPlayVsPointBonusRateLevel07": "多人游玩对战点数奖励比例等级07",
  "MovieAssetNameHard": "Hard 专用 MV 名",
  "PreviewSeconds": "选曲试听单次播放持续时长（单位",
  "TitleEventMessageTag": "活动标题消息标签",
  "RequiredComboNumForEffect": "所需连击数量用于特效",
  "TargetNormaRate": "目标 Norma 比率",
  "AverageLevel": "协力配置对应的平均等级档位",
  "MaxScore": "uint32 最高分",
  "EndDateTime": "活动结束时间，格式同 StartDateTime",
  "bCollaboration": "合作曲标志",
  "GuideLaneBrightnessParamGradationNormal": "普通画面下的渐变参数，当前为 3",
  "AdaptStartTime": "生效开始时间",
  "MenuDescription": "菜单项说明对应的文本键",
  "GetItemVariety": "每档奖励的种类文字",
  "Bpm": "BPM 显示文字",
  "SheetStartNum": "该配置开始适用的 Sheet 编号",
  "NormaDownRate": "Norma 减少率参数",
  "Level10": "等级10",
  "MarvelousShootEffectName": "Marvelous Shoot 特效资源名",
  "JapaneseMessage": "日语",
  "EnglishMessageUSA": "英语（美国）",
  "EnglishMessageSG": "英语（新加坡）",
  "TraditionalChineseMessageTW": "繁体中文（台湾）",
  "TraditionalChineseMessageHK": "繁体中文（香港）",
  "SimplifiedChineseMessage": "简体中文",
  "KoreanMessage": "韩语",
  "VoiceIdArray": "语音 ID 数组",
  "ExpressionType": "表情类型",
  "bAllowCharaBlink": "允许角色眨眼"
}
export function fieldLabel(name:string){const chinese=labels[name]??musicLabel(name);return chinese===name?`字段 / ${name}`:`${chinese} / ${name}`}
